
[Dev]
; Enable this flag to activate dev menu via the ESC key
DevMenu=true
; Enable this flag to activate features used for debugging the engine (may result in slightly slower game speed)
EngineDebugMode=false
; Enable this flag to force the engine to load from the scripts folder instead of from bytecode
TxtScripts=false
; Sets the starting category ID
StartingCategory=0
; Sets the starting scene ID
StartingScene=0
; Determines how fast the game will be when fastforwarding is active
FastForwardSpeed=8
; Determines if the game will try to use the steam directory for the game if it can locate it
UseSteamDir=false
; Determines if applicable rendering modes (such as 3D floor from special stages) will render in "High Quality" mode or standard mode
UseHQModes=true
; Determines what RSDK file will be loaded
DataFile=Data.rsdk

[Game]
; Sets the game language (0 = EN, 1 = FR, 2 = IT, 3 = DE, 4 = ES, 5 = JP)
Language=0
; Determines game type in scripts (0 = Standalone/Original releases, 1 = Origins release)
GameType=0
; Sets the game's spindash style (-1 = let save file decide, 0 = S2, 1 = CD)
OriginalControls=-1
; Determines if the game should hide the touch controls UI
DisableTouchControls=true
; Handles pausing behaviour when focus is lost
; 0 = Game focus enabled, engine focus enabled
; 1 = Game focus enabled, engine focus disabled
; 2 = Game focus disabled, engine focus disabled
DisableFocusPause=0
; The platform type. 0 is standard (PC/Console), 1 is mobile
Platform=0